name: control_car
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.5.3+2

  flutter_settings_screens: ^0.3.3-null-safety+2
  flutter_phone_direct_caller: ^2.1.1

  cupertino_icons: ^1.0.2
  control_button: ^0.0.2
  flutter_bluetooth_serial: ^0.4.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.0
  equatable: ^2.0.3
  sms_autofill: ^2.2.0

  #new
  google_maps_flutter: ^2.0.6
  location: ^4.3.0
  geolocator: ^9.0.2
  geocoding: ^2.0.0
  flutter_polyline_points: ^1.0.0
  http: ^0.13.3
  provider: ^6.0.4
  permission_handler: ^10.2.0
  syncfusion_flutter_sliders: ^20.3.61
  url_launcher: ^6.1.7
  telephony: ^0.2.0
  flutter_launcher_icons: ^0.11.0
  control_pad: ^1.1.1+1
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons :
  android : true
  ios : true
  image_path: "assets/icons/DcIcon.png"